# Generated by Django 4.1.3 on 2022-12-17 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('name', models.CharField(max_length=30)),
                ('username', models.CharField(max_length=30, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=30)),
                ('dob', models.DateField()),
                ('qualification', models.CharField(max_length=20)),
                ('mobile', models.IntegerField()),
                ('gender', models.CharField(max_length=6)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('teacher', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=30)),
                ('rollno', models.IntegerField(blank=True, default=0, null=True)),
                ('course', models.CharField(max_length=20, null=True)),
                ('semester', models.CharField(max_length=10)),
                ('branch', models.CharField(max_length=20)),
                ('present', models.IntegerField(blank=True, default=0, null=True)),
                ('absent', models.IntegerField(blank=True, default=0, null=True)),
                ('sr', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='Login',
        ),
    ]
