# Generated by Django 4.1.3 on 2022-12-17 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_faculty_student_delete_customer_delete_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='rollno',
            field=models.CharField(default=0, max_length=5, null=True),
        ),
    ]
